# Generated by Django 4.1 on 2022-10-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
