# Generated by Django 4.1 on 2022-10-23 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='categories',
            field=models.ManyToManyField(to='mainapp.category'),
        ),
        migrations.AddField(
            model_name='serie',
            name='platform',
            field=models.ManyToManyField(to='mainapp.platform'),
        ),
        migrations.AddField(
            model_name='serie',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
