# Generated by Django 4.1 on 2022-10-24 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_serie_categories_serie_platform_serie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='to_recommend',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='user',
            field=models.ForeignKey(default=False, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
